apiVersion: v1
kind: Service
metadata:
  name: i-nergy-load-forecasting-databroker1webui
spec:
  ports:
  - name: webui
    nodePort: 30001
    port: 30001
    targetPort: 8062
  selector:
    app: i-nergy-load-forecasting-databroker1
  type: NodePort
