apiVersion: v1
kind: Service
metadata:
  name: i-nergy-load-forecasting-lightgbm2
spec:
  ports:
  - name: protobuf-api
    nodePort: 30002
    port: 30002
    targetPort: 8061
  selector:
    app: i-nergy-load-forecasting-lightgbm2
  type: NodePort
