apiVersion: v1
kind: Service
metadata:
  name: i-nergy-load-forecasting-databroker1
spec:
  ports:
  - name: protobuf-api
    nodePort: 30000
    port: 30000
    targetPort: 8061
  selector:
    app: i-nergy-load-forecasting-databroker1
  type: NodePort
