apiVersion: v1
kind: Service
metadata:
  name: i-nergy-load-forecasting-lightgbm2webui
spec:
  ports:
  - name: webui
    nodePort: 30003
    port: 30003
    targetPort: 8062
  selector:
    app: i-nergy-load-forecasting-lightgbm2
  type: NodePort
