# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import clustering_pb2 as clustering__pb2


class PredictClusterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetClusterPrediction = channel.unary_unary(
                '/PredictCluster/GetClusterPrediction',
                request_serializer=clustering__pb2.Input.SerializeToString,
                response_deserializer=clustering__pb2.Prediction.FromString,
                )


class PredictClusterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetClusterPrediction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PredictClusterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetClusterPrediction': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClusterPrediction,
                    request_deserializer=clustering__pb2.Input.FromString,
                    response_serializer=clustering__pb2.Prediction.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PredictCluster', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PredictCluster(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetClusterPrediction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PredictCluster/GetClusterPrediction',
            clustering__pb2.Input.SerializeToString,
            clustering__pb2.Prediction.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
