# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: clustering.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63lustering.proto\"*\n\x05Input\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x13\n\x0bload_values\x18\x02 \x03(\x01\"+\n\nPrediction\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0f\n\x07\x63luster\x18\x02 \x01(\x05\x32=\n\x0ePredictCluster\x12+\n\x14GetClusterPrediction\x12\x06.Input\x1a\x0b.Predictionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'clustering_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INPUT']._serialized_start=20
  _globals['_INPUT']._serialized_end=62
  _globals['_PREDICTION']._serialized_start=64
  _globals['_PREDICTION']._serialized_end=107
  _globals['_PREDICTCLUSTER']._serialized_start=109
  _globals['_PREDICTCLUSTER']._serialized_end=170
# @@protoc_insertion_point(module_scope)
