# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import model_pb2 as model__pb2


class PredictLoadStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MLflowDartsModelPredict = channel.unary_unary(
                '/PredictLoad/MLflowDartsModelPredict',
                request_serializer=model__pb2.Input.SerializeToString,
                response_deserializer=model__pb2.Prediction.FromString,
                )


class PredictLoadServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MLflowDartsModelPredict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PredictLoadServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MLflowDartsModelPredict': grpc.unary_unary_rpc_method_handler(
                    servicer.MLflowDartsModelPredict,
                    request_deserializer=model__pb2.Input.FromString,
                    response_serializer=model__pb2.Prediction.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PredictLoad', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PredictLoad(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MLflowDartsModelPredict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PredictLoad/MLflowDartsModelPredict',
            model__pb2.Input.SerializeToString,
            model__pb2.Prediction.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
