# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmodel.proto\"\'\n\x05Input\x12\x0c\n\x04Load\x18\x01 \x03(\x01\x12\x10\n\x08\x44\x61tetime\x18\x02 \x03(\t\",\n\nPrediction\x12\x0c\n\x04Load\x18\x01 \x03(\x01\x12\x10\n\x08\x44\x61tetime\x18\x02 \x03(\x01\x32=\n\x0bPredictLoad\x12.\n\x17MLflowDartsModelPredict\x12\x06.Input\x1a\x0b.Predictionb\x06proto3')



_INPUT = DESCRIPTOR.message_types_by_name['Input']
_PREDICTION = DESCRIPTOR.message_types_by_name['Prediction']
Input = _reflection.GeneratedProtocolMessageType('Input', (_message.Message,), {
  'DESCRIPTOR' : _INPUT,
  '__module__' : 'model_pb2'
  # @@protoc_insertion_point(class_scope:Input)
  })
_sym_db.RegisterMessage(Input)

Prediction = _reflection.GeneratedProtocolMessageType('Prediction', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTION,
  '__module__' : 'model_pb2'
  # @@protoc_insertion_point(class_scope:Prediction)
  })
_sym_db.RegisterMessage(Prediction)

_PREDICTLOAD = DESCRIPTOR.services_by_name['PredictLoad']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INPUT._serialized_start=15
  _INPUT._serialized_end=54
  _PREDICTION._serialized_start=56
  _PREDICTION._serialized_end=100
  _PREDICTLOAD._serialized_start=102
  _PREDICTLOAD._serialized_end=163
# @@protoc_insertion_point(module_scope)
