# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: databroker.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x64\x61tabroker.proto\"\x07\n\x05\x45mpty\"*\n\x05Input\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x13\n\x0bload_values\x18\x02 \x03(\x01\x32\x30\n\x0cGetDailyLoad\x12 \n\x0eget_daily_load\x12\x06.Empty\x1a\x06.Inputb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'databroker_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=20
  _globals['_EMPTY']._serialized_end=27
  _globals['_INPUT']._serialized_start=29
  _globals['_INPUT']._serialized_end=71
  _globals['_GETDAILYLOAD']._serialized_start=73
  _globals['_GETDAILYLOAD']._serialized_end=121
# @@protoc_insertion_point(module_scope)
