# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import databroker_pb2 as databroker__pb2


class GetDailyLoadStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_daily_load = channel.unary_unary(
                '/GetDailyLoad/get_daily_load',
                request_serializer=databroker__pb2.Empty.SerializeToString,
                response_deserializer=databroker__pb2.Input.FromString,
                )


class GetDailyLoadServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_daily_load(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GetDailyLoadServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_daily_load': grpc.unary_unary_rpc_method_handler(
                    servicer.get_daily_load,
                    request_deserializer=databroker__pb2.Empty.FromString,
                    response_serializer=databroker__pb2.Input.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GetDailyLoad', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GetDailyLoad(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_daily_load(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GetDailyLoad/get_daily_load',
            databroker__pb2.Empty.SerializeToString,
            databroker__pb2.Input.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
