# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmodel.proto\"\x07\n\x05\x45mpty\"*\n\x08\x46\x65\x61tures\x12\x0c\n\x04Load\x18\x01 \x03(\x01\x12\x10\n\x08\x44\x61tetime\x18\x02 \x03(\t2-\n\nDatabroker\x12\x1f\n\ndatabroker\x12\x06.Empty\x1a\t.Featuresb\x06proto3')



_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_FEATURES = DESCRIPTOR.message_types_by_name['Features']
Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'model_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

Features = _reflection.GeneratedProtocolMessageType('Features', (_message.Message,), {
  'DESCRIPTOR' : _FEATURES,
  '__module__' : 'model_pb2'
  # @@protoc_insertion_point(class_scope:Features)
  })
_sym_db.RegisterMessage(Features)

_DATABROKER = DESCRIPTOR.services_by_name['Databroker']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=15
  _EMPTY._serialized_end=22
  _FEATURES._serialized_start=24
  _FEATURES._serialized_end=66
  _DATABROKER._serialized_start=68
  _DATABROKER._serialized_end=113
# @@protoc_insertion_point(module_scope)
